name: Test

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 5'

env:
  CI: true
  DOCKER_BUILDKIT: 1

jobs:


  pytest:
    runs-on: ubuntu-latest
    steps:

    - name: 'ğŸ§° Checkout'
      uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0

    - name: 'ğŸ›³ï¸ Build osvb'
      run: docker build -t osvb -f .github/Dockerfile .

    - name: 'ğŸš§ Run tests'
      run: docker run --rm -v $(pwd):/src -w /src -e CI osvb pytest -v -s -ra test.py --color=yes


  sigrok:
    runs-on: ubuntu-latest
    steps:

    - name: 'ğŸ§° Checkout'
      uses: actions/checkout@v3

    - name: 'ğŸš§ Generate waveforms'
      run: |
        cd sigrok/resolution
        for img in buster-mcode buster-llvm-7; do
          docker pull ghdl/ghdl:"$img"
          docker run --rm -tv $(pwd):/src -e CI ghdl/ghdl:"$img" /src/run.sh
        done

        cd ../hierarchy
        docker run --rm -tv $(pwd):/src -e CI ghdl/ghdl:buster-mcode /src/run.sh

    - name: 'ğŸ›³ï¸ Build docker image with libsigork and sigrok-cli'
      run: |
        cd sigrok
        docker build -t umarcor/sigrok .

    - name: 'ğŸš§ Run sigrok-cli'
      run: |
        cd sigrok
        docker run --rm -tv $(pwd):/src -e CI umarcor/sigrok /src/test.sh
